### ISSUE TITLE
DLL import error on Windows

### ISSUE THREAD

**Issue by Melan2001** [Cheaterman/panda3d-kivy#3]
On Windows (and P3D version 1.10.5), the basic example is not working and create a DLL import error:

```
[INFO   ] Logger: Record log in \.kivy\logs\kivy_20-03-01_11.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "\Panda3D-1.10.5-x64\python\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "\Panda3D-1.10.5-x64\python\ppython.exe"
[INFO   ] Factory: 184 symbols loaded
[DEBUG  ] Cache: register <kv.lang> with limit=None, timeout=None
[DEBUG  ] Cache: register <kv.image> with limit=None, timeout=60
[DEBUG  ] Cache: register <kv.atlas> with limit=None, timeout=None
[DEBUG  ] image: Failed trying to import the "sdl2" provider from "\Panda3D-1.10.5-x64\python\lib\site-packages\kivy\core\image\_img_sdl2.cp37-win_amd64.pyd". This error is often encountered when a dependency is missing, or if there are multiple copies of the same dependency dll on the Windows PATH and they are incompatible with each other. This can occur if you are mixing installations (such as different python installations, like anaconda python and a system python) or if another unrelated program added its directory to the PATH. Please examine your PATH and python installation for potential issues. To further troubleshoot a "DLL load failed" error, please download "Dependency Walker" (64 or 32 bit version - matching your python bitness) from dependencywalker.com and set the environment variable KIVY_SDL2_DEPENDENCY_WALKER to the full path of the downloaded depends.exe file and rerun your application to generate an error report
[INFO   ] Image: Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[DEBUG  ] Cache: register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] Cache: register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] Window: Provider <sdl2> ignored by config
[CRITICAL] Window: Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
 
[INFO   ] GL: Using the "OpenGL" graphics system
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "KivyTests.py", line 103, in <module>
[WARNING] stderr:     PandaApp().run()
[WARNING] stderr:   File "KivyTests.py", line 57, in __init__
[WARNING] stderr:     panda_app=self,
[WARNING] stderr:   File "\Panda3D-1.10.5-x64\python\lib\site-packages\panda3d_kivy\app.py", line 18, in __init__
[WARNING] stderr:     panda_app=panda_app,
[WARNING] stderr:   File "\Panda3D-1.10.5-x64\python\lib\site-packages\panda3d_kivy\core\window.py", line 152, in __init__
[WARNING] stderr:     super().__init__(**kwargs)
[WARNING] stderr:   File "\Panda3D-1.10.5-x64\python\lib\site-packages\kivy\core\window\__init__.py", line 981, in __init__
[WARNING] stderr:     self.create_window()
[WARNING] stderr:   File "\Panda3D-1.10.5-x64\python\lib\site-packages\kivy\core\window\__init__.py", line 1254, in create_window
[WARNING] stderr:     self.initialize_gl()
[WARNING] stderr:   File "\Panda3D-1.10.5-x64\python\lib\site-packages\kivy\core\window\__init__.py", line 1225, in initialize_gl
[WARNING] stderr:     ignored=self.gl_backends_ignored)
[WARNING] stderr:   File "\Panda3D-1.10.5-x64\python\lib\site-packages\kivy\core\gl\__init__.py", line 38, in init_gl
[WARNING] stderr:     gl_init_symbols(allowed, ignored)
[WARNING] stderr:   File "kivy\graphics\opengl.pyx", line 1556, in kivy.graphics.opengl.gl_init_symbols
[WARNING] stderr:   File "kivy\graphics\cgl.pyx", line 99, in kivy.graphics.cgl.cgl_init
[WARNING] stderr:   File "\Panda3D-1.10.5-x64\python\lib\importlib\__init__.py", line 127, in import_module
[WARNING] stderr:     return _bootstrap._gcd_import(name[level:], package, level)
[WARNING] stderr:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[WARNING] stderr:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[WARNING] stderr:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[WARNING] stderr:   File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
[WARNING] stderr:   File "<frozen importlib._bootstrap>", line 583, in module_from_spec
[WARNING] stderr:   File "<frozen importlib._bootstrap_external>", line 1043, in create_module
[WARNING] stderr:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[WARNING] stderr: ImportError: DLL load failed: module specified can not be found.
```

**Comment by Melan2001** [comment]
I made Tito's sample work. Issue was simply that there were some dependencies not installed by pip. So I manually did:
ppython -m pip install kivy.deps.glew
ppython -m pip install kivy.deps.sdl2
I also manually install kaki before these 2 dependencies (in case of) but does not seem related

However, your basic sample is not working...as it creates an OS error exception : [WARNING] stderr:   File "_ctypes/callbacks.c", line 232, in 'calling callback function'
[WARNING] stderr:   File "\Panda3D-1.10.5-x64\python\lib\site-packages\kivy\input\providers\wm_touch.py", line 127, in _touch_wndProc
[WARNING] stderr:     lParam)

**Comment by Cheaterman** [comment]
That part at the end is very weird.

**Comment by Cheaterman** [comment]
Try the movement example. If it doesn't work either, try adding this just below `from panda3d_kivy.app import App` in both examples:
```from kivy.config import Config
Config.remove_option('input', '%(name)s')
```

**Comment by Melan2001** [comment]
Same issue with the basic sample with
from kivy.config import Config
Config.remove_option('input', '%(name)s')

**Comment by Cheaterman** [comment]
FWIW, I am not surprised the "basic" example doesn't work, as it instantiates two Kivy apps, which is not really supported by Kivy itself and needed a lot of hacks to work on Linux (and possibly will need extra hacks to work on Windows).

Seeing as the most likely use case for this plugin is to display a Kivy UI for your Panda application, most people will probably only ever need a single Kivy app anyway ; besides, I personally don't have a Windows machine I can test this on, so it certainly doesn't help solve the issue hehe.

If someone wants to fix the "basic" sample for Windows and submit a PR, I'd be more than happy to merge it ; in the meantime, I'll close this issue as it's "solved" for a single Kivy app :-)
